// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Future<List<DocPoint>> detectDocumentEdges({required List<int> imageBytes}) =>
    RustLib.instance.api.crateApiScanDetectDocumentEdges(
      imageBytes: imageBytes,
    );

class DocPoint {
  final double x;
  final double y;

  const DocPoint({required this.x, required this.y});

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocPoint &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}
